name: Default

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - trunk
      - develop
      - maine
      - mane

jobs:
  build:
    env:
      github_token: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
